config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lift_types
  get 'reports/all_operation'
  post 'reports/all_operation'
  get 'reports/cards'
  get 'reports/add_form'
  get 'reports/sub_form'

  resources :lifts, only: :index do
    collection {post :import}
    collection {get :set_type}
  end

  root 'lifts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form_date.rb
class FormDate
    include ActiveModel::Model
    attr_accessor :type, :start, :stop
end

app/models/lift.rb
class Lift < ApplicationRecord
  belongs_to :lift_type
end

app/models/lift_type.rb
class LiftType < ApplicationRecord
  has_many :lifts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lift_types_controller.rb
class LiftTypesController < ApplicationController
  before_action :set_lift_type, only: %i[show edit update destroy]
  before_action :set_lifts, only: %i[new edit]

  # GET /lift_types
  # GET /lift_types.json
  def index
    @lift_types = LiftType.where(user_id: current_user.id).or(LiftType.where(user_id: nil))
  end

  # GET /lift_types/1
  # GET /lift_types/1.json
  def show;
  end

  # GET /lift_types/new
  def new
    @lift_type = LiftType.new
  end

  # GET /lift_types/1/edit
  def edit;
  end

  # POST /lift_types
  # POST /lift_types.json
  def create
    @lift_type = LiftType.new(lift_type_params)
    @lift_type.user_id = current_user.id
    respond_to do |format|
      if @lift_type.save
        format.html {redirect_to lift_types_path, notice: 'Lift type was successfully created.'}
        format.json {render :show, status: :created, location: @lift_type}
      else
        format.html {render :new}
        format.json {render json: @lift_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /lift_types/1
  # PATCH/PUT /lift_types/1.json
  def update
    respond_to do |format|
      if @lift_type.update(lift_type_params)
        format.html {redirect_to lift_types_path, notice: 'Lift type was successfully updated.'}
        format.json {render :show, status: :ok, location: @lift_type}
      else
        format.html {render :edit}
        format.json {render json: @lift_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /lift_types/1
  # DELETE /lift_types/1.json
  def destroy
    @lift_type.destroy
    respond_to do |format|
      format.html {redirect_to lift_types_url, notice: 'Lift type was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_lift_type
    @lift_type = LiftType.find(params[:id])
    redirect_to lift_types_path unless @lift_type.user_id
  end

  def set_lifts
    @lifts = Lift.where(lift_type_id: -1)
  end

  def lift_type_params
    params.require(:lift_type).permit(:condition, :name)
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  include LiftsModule

  def index
    session[:i] = 0
    @lifts = Lift.where('user_id = ?', current_user.id).order(date_of_commissioned: :desc)
  end

  def import
    file = params[:file]
    import_lifts(file, current_user.id) unless file.nil?
    redirect_to root_url, notice: 'Products imported.'
  end

  def set_type
    set_type_lifts(current_user.id)
    redirect_to root_url, notice: 'Products imported.'
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ReportsModule
  before_action :init
  before_action :set_session, only: %w[all_operation cards]
  protect_from_forgery except: :show

  def cards
    @lifts = @lifts.where(transaction_type: 'Płatność kartą')
    @chart_data = chart_data @lifts
    @lifts = @lifts.order(date_of_commissioned: :desc)
  end

  def all_operation
    @lifts = @lifts.where('amount < 0').where(sql_date).where(@sql)
    @chart_data = chart_data @lifts
    @lifts = @lifts.order(date_of_commissioned: :desc)
  end

  private

  def init
    @lifts = Lift.where('user_id = ? and lift_type_id <> -2', current_user.id)
    @form_date = FormDate.new
  end

  def set_session
    session[:form_date] = params.require(:form_date).permit(:type, :start, :stop) if params.keys.include? 'form_date'
    session[:sql] = sql_build unless (params.keys & %w[simple product value]).empty?
    session.delete(:sql) if params.keys.include? 'clear_sql'
    session.delete(:form_date) if params.keys.include? 'clear_date'
    @form_date = FormDate.new(session[:form_date])
    @sql = session[:sql]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lift_types_helper.rb
module LiftTypesHelper
end

app/helpers/lifts_helper.rb
module LiftsHelper

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_menu.html.erb
<%= nav_bar fixed: :top, brand: 'Moje konto', responsive: true, fluid: true do %>
  <%= menu_group do %>
    <%= menu_item 'Start', root_path %>
    <%= menu_item 'Wszystkie wydatki', reports_all_operation_path %>
    <%= menu_item 'Karty', reports_cards_path %>
    <%= menu_divider %>

    <%= drop_down 'Ustawienia' do %>
      <%= menu_item 'Typy wyciągu', lift_types_path %>
      <%= menu_item 'Zmiana typów wyciągów', set_type_lifts_path %>
      <%= menu_item 'Ustawienia konta', edit_user_registration_path %>
      <%= menu_item 'Wyloguj', destroy_user_session_path, method: :delete %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Analiza wyciągów</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/menu' %>
<div class="container-fluid" style="padding-top: 50px;">
  <%= yield %>
</div>
</body>
<script>
    $('#report').bootstrapTable({
        onSearch: function () {
            amountCount();
        }
    });
    amountCount();
</script>
</html>

app/views/lift_types/_form.html.erb
<div class="container">
  <%= bootstrap_form_for(@lift_type) do |f| %>
    <%= f.text_field :name, label: 'Nazwa' %>
    <%= f.text_field :condition, label: 'Zapytanie' %>
    na przykład:
    <pre>name like '%ROSSMANN%'</pre>
    <%= f.submit 'Zapisz', class: 'btn btn-primary' %>
    <%= link_to 'Anuluj', lift_types_path, :class => 'btn btn-default' %>
  <% end %>
</div>

<table data-toggle="table" data-search="true">
  <thead>
  <tr>
    <th>Typ transakcji (transaction_type)</th>
    <th>Nazwa i rachunek nadawcy/odbiorcy (name/account)</th>
    <th>Opis transakcji (description)</th>
    <th>Dane dodatkowe (addtional_data)</th>
  </tr>
  </thead>
  <tbody>
  <% @lifts.each do |lift| %>
    <tr>
      <td><%= lift.transaction_type %></td>
      <td>
        <%= lift.name %>
        <%= lift.account %>
      </td>
      <td><%= lift.description %></td>
      <td><%= lift.addtional_data %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lift_types/edit.html.erb
<h1>Editing Lift Type</h1>

<%= render 'form', lift_type: @lift_type %>

<%= link_to 'Show', @lift_type %> |
<%= link_to 'Back', lift_types_path %>

app/views/lift_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Typy wydatków</h1>

<%= link_to 'Nowy typ wyciągu', new_lift_type_path, class: 'btn btn-success' %>
<br>
<br>
<table data-toggle="table" data-search="true">
  <thead>
  <tr>
    <th>Name</th>
    <th>Zapytanie</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @lift_types.each do |lift_type| %>
    <tr>
      <td><%= lift_type.name %></td>
      <td><%= lift_type.condition %></td>
      <td><%= link_to 'Edit', edit_lift_type_path(lift_type) %></td>
      <td><%= link_to 'Destroy', lift_type, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/lift_types/new.html.erb
<h1>New Lift Type</h1>

<%= render 'form', lift_type: @lift_type %>

<%= link_to 'Back', lift_types_path %>

app/views/lift_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lift_type.name %>
</p>

<%= link_to 'Edit', edit_lift_type_path(@lift_type) %> |
<%= link_to 'Back', lift_types_path %>

app/views/lifts/import.html.erb
<h1>Lifts#import</h1>
<p>Find me in app/views/lifts/import.html.erb</p>

app/views/lifts/index.html.erb
<div>
  <h3>Import z pliku CSV</h3>
  <%= bootstrap_form_tag url: import_lifts_path, html: {enctype: 'multipart/form-data'} do |f| %>
    <div class="input-group">
  <span class="input-group-btn">
    <span class="btn btn-small btn-primary btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Plik wyciągu</span>
    <%= f.file_field_tag :file, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: 'display: none;' %>
  </span>
      <span class="form-control"></span>
    </div>
    <%= f.submit_tag 'Import CSV', class: 'btn btn-success' %>
  <% end %>
</div>


<table data-toggle="table" data-search="true">
  <thead>
  <tr>
    <th>Id</th>
    <th>Data księgowania</th>
    <th>Data zlecona</th>
    <th>Typ transakcji</th>
    <th>Kwota</th>
    <th>Nazwa i rachunek nadawcy/odbiorcy</th>
    <th>Opis transakcji</th>
    <th>Dane dodatkowe</th>
    <th>Typ</th>
  </tr>
  </thead>
  <tbody>
  <% @lifts.each do |lift| %>
    <tr>
      <td><%= lift.id_lift %></td>
      <td><%= lift.date_of_booking %></td>
      <td><%= lift.date_of_commissioned %></td>
      <td><%= lift.transaction_type %></td>
      <td id="ammount"><%= lift.amount %></td>
      <td>
        <%= lift.name %>
        <%= lift.account %>
      </td>
      <td><%= lift.description %></td>
      <td><%= lift.addtional_data %></td>
      <td><%= lift.lift_type.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/reports/_advanced_filters.erb
<%= bootstrap_form_tag url: url do |f| %>
  <%= f.hidden_field :type, value: :advanced %>
  <%= f.text_field :value, label: 'Wartość' %>
  <%= f.submit 'Zastosuj', class: 'btn btn-primary' %>
<% end %>

app/views/reports/_charts.erb
<div class="col-md-4">
  <h2>Podział wg nazwy:</h2>
  <%= pie_chart @chart_data[:name], legend: false %>
</div>
<div class="col-md-4">
  <h2>Podział wg typu:</h2>
  <%= pie_chart @chart_data[:type], legend: false %>
</div>
<div class="col-md-4">
<%= line_chart @chart_data[:line] %>
  </div>

app/views/reports/_clear_session.erb
<%= bootstrap_form_tag url: reports_all_operation_path, html: {id: 'clear_sql'} do |f| %>
  <%= f.hidden_field :clear_sql %>
<% end %>
<%= bootstrap_form_tag url: reports_all_operation_path, html: {id: 'clear_date'} do |f| %>
  <%= f.hidden_field :clear_date %>
<% end %>

app/views/reports/_filter_panel.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Filtry</h3>
  </div>
  <div class="panel-body">
    <div class="col-md-4">
      <div class="input-group">
  <span class="input-group-btn">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filterModal">Filtruj</button>
  </span>
        <input type="text" class="form-control" placeholder="Filtr" value="<%= @sql %>" readonly>
      </div>
      <input type="submit" name="commit" value="Wyczyść filtry" class="btn btn-info" data-disable-with="Wyczyść filtry" form="clear_sql">
    </div>
    <%= render 'form_from_to_date' %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="filterModalLabel">Filtry</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
        <div class="modal-footer">
          <%= render 'clear_session' %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_form.erb
<%= tabs do |tab| %>
  <% tab.tab 'Ustaw filte' do %>
    <%= render 'simple_filters', url: reports_all_operation_path %>
  <% end %>
  <% tab.tab 'Filtry zapisaneme' do %>
    <%= render 'saved_filters', url: reports_all_operation_path %>
  <% end %>
  <% tab.tab 'Zaawansowane' do %>
    <%= render 'advanced_filters', url: reports_all_operation_path %>
  <% end %>
<% end %>

app/views/reports/_form_from_to_date.erb
<%= bootstrap_form_for @form_date, url: reports_all_operation_path do |f| %>
    <div class="col-md-2">
    <%= f.radio_button :type, 'commissioned', label: 'Data transakcji', checked: true %>
    <%= f.radio_button :type, 'booking', label: 'Data księgowania' %>
    </div>
    <div class="col-md-2">
      <%= f.date_field :start, value: @form_date.start %>
    </div>
    <div class="col-md-2">
      <%= f.date_field :stop, value: @form_date.stop %>
    </div>
    <div class="col-md-2" style="margin-top: 25px;">
      <%= f.submit 'Ustaw datę', class: 'btn btn-success' %>
      <input type="submit" name="commit" value="Wyczyść daty" class="btn btn-info" form="clear_date" data-remote="true">
    </div>
<% end %>

app/views/reports/_saved_filters.erb
<%= bootstrap_form_tag url: url do |f| %>
  <%= f.hidden_field :type, value: :saved %>
  <%= f.collection_select :product, LiftType.all, :id, :name, label: 'Filtry zapisane:' %>
  <%= f.submit 'Zastosuj', class: 'btn btn-primary' %>
<% end %>

app/views/reports/_simple_filds.erb
<%= f.select '[simple][]filed', Lift.column_names, label: 'Jeżeli pole:', selected: 'name' %>
<%= f.select '[simple][]condition', [['zawiera', 'like'], ['nie zawiera', 'not like'], ['=', '=']], label: 'warunek' %>
<%= f.text_field '[simple][]value', label: 'Wartość' %>

app/views/reports/_simple_filters.erb
<%= bootstrap_form_tag url: url do |f| %>
  <%= f.hidden_field :type, value: :simple %>
  <div id="skillSet">
    <%= render 'simple_filds', f: f %>
  </div>
  <%= link_to "<span class=\"glyphicon glyphicon-plus\"></span>".html_safe, 'javascript:;', id: 'addFilter' %>
  <div class="actions">
    <%= f.submit 'Filtruj', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= bootstrap_form_tag url: url do |f| %>
  <div class="hide" id="new_filter_form">
    <%= f.select '[simple][]operator', [['i', 'and'], ['lub', 'or']], label: 'warunek' %>
    <%= render 'simple_filds', f: f, locals: {skill: false} %>
  </div>
<% end %>
<script>
    $(document).ready(function () {
        $("#addFilter").click(function () {
            $("#skillSet").append($("#new_filter_form").html());
        });
    });
</script>

app/views/reports/all_operation.html.erb
<%= render 'filter_panel' %>
<div class="row">
<%= render 'charts' %>
</div>

<div class="row">
  <h2>Saldo transakcji: <span id="amountcount"></span></h2>
  <table id="report" data-toggle="table" data-search="true">
    <thead>
    <tr>
      <th>Id</th>
      <th>Data księgowania</th>
      <th>Data zlecona</th>
      <th>Typ transakcji</th>
      <th>Kwota</th>
      <th>Nazwa i rachunek nadawcy/odbiorcy</th>
      <th>Opis transakcji</th>
      <th>Dane dodatkowe</th>
      <th>Typ</th>
    </tr>
    </thead>
    <tbody>
    <% @lifts.each do |lift| %>
      <tr>
        <td><%= lift.id_lift %></td>
        <td><%= lift.date_of_booking %></td>
        <td><%= lift.date_of_commissioned %></td>
        <td><%= lift.transaction_type %></td>
        <td class="amount"><%= lift.amount %></td>
        <td>
          <%= lift.name %>
          <%= lift.account %>
        </td>
        <td><%= lift.description %></td>
        <td><%= lift.addtional_data %></td>
        <td><%= lift.lift_type.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/reports/cards.html.erb
<%= render 'filter_panel' %>
<div class="row">
  <%= render 'charts' %>
</div>
<div class="row">

  <h2>Saldo transakcji: <span id="amountcount"></span></h2>
  <table id="report" data-toggle="table" data-search="true">
    <thead>
    <tr>
      <th>Id</th>
      <th>Data księgowania</th>
      <th>Data zlecona</th>
      <th>Typ transakcji</th>
      <th>Kwota</th>
      <th>Nazwa i rachunek nadawcy/odbiorcy</th>
      <th>Opis transakcji</th>
      <th>Dane dodatkowe</th>
      <th>Typ</th>
    </tr>
    </thead>
    <tbody>
    <% @lifts.each do |lift| %>
      <tr>
        <td><%= lift.id_lift %></td>
        <td><%= lift.date_of_booking %></td>
        <td><%= lift.date_of_commissioned %></td>
        <td><%= lift.transaction_type %></td>
        <td class="amount"><%= lift.amount %></td>
        <td>
          <%= lift.name %>
          <%= lift.account %>
        </td>
        <td><%= lift.description %></td>
        <td><%= lift.addtional_data %></td>
        <td><%= lift.lift_type.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>